### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [BurakDev/BloonPHP#1]

**Comment by sant0ro** [comment]
What kind of Issue is this.

No one tried create an Emulator in php.
As i can see is using React, good for Thread System.

Also php has good NIO Frameworks. Better than Java NIOs.

The onliest thing that suck in php is Threading, but is also improved as third-party ZEND engine modules. Like zend-php-iathread.

Also php is good for scaling, php is awesome. Why you think Facebook created HHVM? (an php virtual machine) that is really a lot better than JVM (java virtual machines).

Yeah, also exists JPHP (Java VM php)...

Please point more good statements and not trolls.

**Comment by emansom** [comment]
Facebook created HHVM because they realized they could either hire expensive C++ developers to handle the scale, or keep the sucky PHP developers and only hire a few C++ developers part time to terraform the PHP language and it's implementation in something true async and JIT-able.

That is a hack/workaround, which Facebook found cost-effective.

You shouldn't rely on ducttape to fix your car.

**Comment by sant0ro** [comment]
That's why HHVM is considered an PhP Hack, and everyone calls HHVM as "Hacks" (formely name for HHVM)... But that's other story.

Yeah, ZEND engine isn't the best of the world, but think how create a good engine in C++? A Language that aren't the best for OO*, for Design Patterns and also the most easy language to find Leaks, Memory Leaks, Security Issues, etc.

C++ isn't like Java and their Super Dupper Mega Interpreter that makes everything gooooood.

But we can give a vouch to @BurakDev before critizism.

**Comment by droppyiam** [comment]
PhP rocks
